🔧 adjust public app script for secondaryFiles
kids-first/kf-cavatica-public-app-publisher pull request #6
Opened 2021-07-01 21:46 UTC by dmiller15

## Description

Two things here:
1. adjust the public app script to allow suggested secondaryFiles for each entry
2. added template files for GATK files (the funcotator file still needs to be added to kf-references project)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2021-07-08 14:45 UTC, migbro requested changes
Looks good for the most part, should probably update this desc: 
```
  -f FILES, --files FILES
                        Cavatica-style tsv manifest with file ID, file name,
                        and associated cwl input key
```
And the README reference to that to reflect added columns. It seems the input file can be a bit dynamic the way you wrote it? Like if you gave it the ones I had originally with fewer cols, it'd still work?

2021-07-08 14:51 UTC, dmiller15 commented
> Looks good for the most part, should probably update this desc:
> 
> ```
>   -f FILES, --files FILES
>                         Cavatica-style tsv manifest with file ID, file name,
>                         and associated cwl input key
> ```
> 
> And the README reference to that to reflect added columns. It seems the input file can be a bit dynamic the way you wrote it? Like if you gave it the ones I had originally with fewer cols, it'd still work?

@migbro It's not very dynamic. You can either provide nothing or explicitly write `None` with this implementation. So yes all of the old template files will work with this implementation.

2021-07-08 14:58 UTC, migbro approved these changes
`comma-separate` - make this `comma-separated` please

2021-07-13 13:56 UTC, sickler-alex approved these changes

2021-07-13 13:57 UTC, merged